#!/usr/bin/env bash
# Queue-projection, byte-preservation, reply-prefix, and fail-closed tests.
set -u

# shellcheck source=tests/lib.sh disable=SC1091
. "$(dirname "${BASH_SOURCE[0]}")/lib.sh"

GENERATOR="$ROOT/bin/fm-pending-decisions-generate.sh"
RULING_CHECK="$ROOT/bin/fm-captain-ruling-check.sh"
TMP_ROOT=$(fm_test_tmproot fm-pending-decisions-generate)
QUEUE_BEGIN='<!-- BEGIN GENERATED: captain-queue -->'
QUEUE_END='<!-- END GENERATED: captain-queue -->'
REPLY_BEGIN='<!-- BEGIN APPEND-ONLY: captain-replies -->'
REPLY_END='<!-- END APPEND-ONLY: captain-replies -->'

command -v jq >/dev/null 2>&1 || { echo "skip: jq not found"; exit 0; }
command -v tasks-axi >/dev/null 2>&1 || { echo "skip: tasks-axi not found"; exit 0; }

tasks_in() { # <home> <tasks-axi args...>
  local home=$1
  shift
  (cd "$home" && tasks-axi "$@")
}

digest() { # <file>
  shasum -a 256 "$1" | awk '{print $1}'
}

write_document() { # <home>
  cat > "$1/data/pending-decisions.md" <<'EOF'
# Captain's queue

**How to reply:** keep this hand-written preamble byte-for-byte.

## ✍️ Your replies

<!-- BEGIN APPEND-ONLY: captain-replies -->
historical-decision: captain already wrote this reply
<!-- END APPEND-ONLY: captain-replies -->

---

<!-- BEGIN GENERATED: captain-queue -->
<!-- captain-decision: D2 retired-decision -->
<!-- captain-decision: D4 decision-alpha -->
# ⏸ Needs your call

Stale generated bytes must be replaced.
<!-- END GENERATED: captain-queue -->

## Firstmate recommendations

### D4 recommendation

Keep this recommendation exactly as written.

# 🔜 In progress

| Work | State |
|---|---|
| Hand-written row | Moving |

# 🏗 Program

The program prose stays untouched.

# 🙋 Your hands-on tasks

- Keep this hand-written task.

# ✅ Settled

The settled history also stays untouched.
EOF
}

make_home() { # <name>
  local home="$TMP_ROOT/$1"
  mkdir -p "$home/data" "$home/state"
  chmod 0700 "$home/state"
  cp "$ROOT/.tasks.toml" "$home/.tasks.toml"
  cat > "$home/data/backlog.md" <<'EOF'
## In flight

## Queued

## Done
EOF
  tasks_in "$home" add decision-alpha "Alpha decision title" \
    --kind captain --repo SABS-Technology-sabstech >/dev/null
  tasks_in "$home" hold decision-alpha \
    --reason "Alpha hold reason from the canonical queue" --kind captain >/dev/null
  tasks_in "$home" add decision-beta "Beta decision title" \
    --kind task --repo firstmate >/dev/null
  tasks_in "$home" hold decision-beta \
    --reason "Beta hold reason on an ordinary task kind" --kind captain >/dev/null
  write_document "$home"
  printf '%s\n' "$home"
}

run_generator() { # <home>
  FM_HOME="$1" "$GENERATOR"
}

extract_region() { # <file> <begin> <end> <output>
  perl -0777 -e '
    my ($path, $begin, $end) = @ARGV;
    open my $fh, "<", $path or die $!;
    local $/;
    my $data = <$fh>;
    $data =~ /\Q$begin\E\n(.*?)\Q$end\E/s or die "region missing\n";
    print $1;
  ' "$1" "$2" "$3" > "$4"
}

normalize_manual_bytes() { # <file> <strip-generated-prefixes: yes|no> <output>
  perl -0777 -e '
    my ($path, $strip, $qb, $qe) = @ARGV;
    open my $fh, "<", $path or die $!;
    local $/;
    my $data = <$fh>;
    $data =~ s/(\Q$qb\E\n).*?(\Q$qe\E)/$1<generated>\n$2/s
      or die "generated region missing\n";
    if ($strip eq "yes") {
      $data =~ s/^decision-alpha: \n//m or die "alpha prefix missing\n";
      $data =~ s/^decision-beta: \n//m or die "beta prefix missing\n";
    }
    print $data;
  ' "$1" "$2" "$QUEUE_BEGIN" "$QUEUE_END" > "$3"
}

test_projection_preserves_manual_bytes_and_backlog() {
  local home pending backlog before_doc before_backlog after_backlog generated
  local before_normal after_normal replies_before replies_after replies_expected
  local generated_text tick='`'
  home=$(make_home projection)
  pending="$home/data/pending-decisions.md"
  backlog="$home/data/backlog.md"
  before_doc="$home/before.md"
  generated="$home/generated.txt"
  before_normal="$home/before.normal"
  after_normal="$home/after.normal"
  replies_before="$home/replies.before"
  replies_after="$home/replies.after"
  replies_expected="$home/replies.expected"
  cp "$pending" "$before_doc"
  before_backlog=$(digest "$backlog")
  extract_region "$pending" "$REPLY_BEGIN" "$REPLY_END" "$replies_before"

  run_generator "$home" >/dev/null || fail "generator failed on a valid marked document"

  after_backlog=$(digest "$backlog")
  [ "$before_backlog" = "$after_backlog" ] || fail "generation changed data/backlog.md"
  extract_region "$pending" "$QUEUE_BEGIN" "$QUEUE_END" "$generated"
  generated_text=$(cat "$generated")
  assert_contains "$generated_text" '**2 open decisions; 1 queue orphan.**' \
    "generated count does not match the canonical queue"
  [ "$(grep -Fc '### D4 - Alpha decision title' "$generated")" = 1 ] \
    || fail "alpha decision was absent or duplicated"
  [ "$(grep -Fc '### D5 - Beta decision title' "$generated")" = 1 ] \
    || fail "beta decision was absent or duplicated"
  assert_contains "$generated_text" "- **Backing hold task:** ${tick}decision-alpha${tick}" \
    "alpha backing hold id is missing"
  assert_contains "$generated_text" "- **Origin task:** ${tick}decision-alpha${tick}" \
    "alpha origin task is missing"
  assert_contains "$generated_text" '- **Hold reason:** Alpha hold reason from the canonical queue' \
    "alpha hold reason is missing"
  assert_contains "$generated_text" "- **Hold kind:** ${tick}captain${tick}" \
    "hold kind is missing"
  assert_contains "$generated_text" "- **Repository:** ${tick}sabstech${tick}" \
    "normalized sabstech repository is missing"
  assert_contains "$generated_text" "- **Repository:** ${tick}firstmate${tick}" \
    "firstmate repository is missing"

  normalize_manual_bytes "$before_doc" no "$before_normal"
  normalize_manual_bytes "$pending" yes "$after_normal"
  cmp -s "$before_normal" "$after_normal" \
    || fail "bytes outside the generated region and appended prefixes changed"

  extract_region "$pending" "$REPLY_BEGIN" "$REPLY_END" "$replies_after"
  cp "$replies_before" "$replies_expected"
  printf 'decision-alpha: \ndecision-beta: \n' >> "$replies_expected"
  cmp -s "$replies_expected" "$replies_after" \
    || fail "reply-zone content was removed, reordered, rewritten, or not append-only"
  pass "canonical items and counts project once with every required field"
  pass "all hand-written and existing reply bytes survive while backlog stays unchanged"
}

test_reply_prefixes_wake_the_real_detector() {
  local home pending out
  home=$(make_home detector)
  pending="$home/data/pending-decisions.md"
  run_generator "$home" >/dev/null || fail "generator failed before detector integration"
  perl -0pi -e '
    s/decision-alpha: \n/decision-alpha: choose alpha\n/;
    s/decision-beta: \n/decision-beta: choose beta\n/;
  ' "$pending"
  out=$(FM_HOME="$home" "$RULING_CHECK") || fail "real ruling detector failed"
  [ "$out" = 'captain-ruling decision-alpha,decision-beta' ] \
    || fail "generated reply prefixes did not wake the real detector for every queue item: $out"
  pass "generated hold-id prefixes wake the real detector for captain and ordinary task kinds"
}

test_regeneration_is_stable_and_reply_append_only() {
  local home pending first second
  home=$(make_home stable)
  pending="$home/data/pending-decisions.md"
  run_generator "$home" >/dev/null || fail "first generation failed"
  first=$(digest "$pending")
  run_generator "$home" >/dev/null || fail "second generation failed"
  second=$(digest "$pending")
  [ "$first" = "$second" ] || fail "unchanged regeneration rewrote the document"
  pass "unchanged regeneration is byte-stable and does not duplicate reply prefixes"
}

test_blocked_ordinary_hold_is_generated_once() {
  local home generated
  home=$(make_home blocked-ordinary)
  generated="$home/generated.txt"
  tasks_in "$home" add readiness-blocker "Independent ready blocker" \
    --kind task --repo firstmate >/dev/null
  tasks_in "$home" add ordinary-blocked "Blocked ordinary captain hold" \
    --kind task --repo firstmate >/dev/null
  tasks_in "$home" hold ordinary-blocked \
    --reason "captain ruling pending behind blocker" --kind captain >/dev/null
  tasks_in "$home" block ordinary-blocked --by readiness-blocker >/dev/null

  run_generator "$home" >/dev/null || fail "generator failed on a blocked ordinary hold"
  extract_region "$home/data/pending-decisions.md" "$QUEUE_BEGIN" "$QUEUE_END" "$generated"
  [ "$(grep -Fc 'Blocked ordinary captain hold' "$generated")" = 1 ] \
    || fail "blocked ordinary captain hold was absent or duplicated in generated output"
  assert_no_grep 'Independent ready blocker' "$generated" \
    "ordinary blocker leaked into the captain decision projection"
  pass "blocked ordinary captain hold is generated once without conflating its blocker"
}

test_unanswerable_orphan_is_visible_without_a_swallowed_prefix() {
  local home pending generated replies
  home=$(make_home unanswerable-orphan)
  pending="$home/data/pending-decisions.md"
  generated="$home/generated.txt"
  replies="$home/replies.txt"
  tasks_in "$home" unhold decision-alpha >/dev/null

  run_generator "$home" >/dev/null || fail "generator failed on a list-only queue orphan"

  extract_region "$pending" "$QUEUE_BEGIN" "$QUEUE_END" "$generated"
  extract_region "$pending" "$REPLY_BEGIN" "$REPLY_END" "$replies"
  assert_contains "$(cat "$generated")" \
    'reply unavailable; this queue orphan has no active captain hold for the ruling detector.' \
    "list-only queue orphan was not visibly marked unanswerable"
  assert_no_grep 'decision-alpha:' "$replies" \
    "list-only orphan received a reply prefix the detector would swallow"
  assert_grep 'decision-beta: ' "$replies" \
    "answerable queue orphan did not receive its hold-id reply prefix"
  pass "unanswerable queue orphans stay visible and never receive a silently swallowed prefix"
}

assert_refusal() { # <name> <expected-message> <document-bytes>
  local name=$1 expected=$2 document=$3 home pending before after out rc
  home="$TMP_ROOT/refuse-$name"
  pending="$home/data/pending-decisions.md"
  mkdir -p "$home/data"
  printf '%s' "$document" > "$pending"
  before=$(digest "$pending")
  set +e
  out=$(FM_HOME="$home" "$GENERATOR" 2>&1)
  rc=$?
  set -e
  expect_code 1 "$rc" "$name marker failure must refuse"
  assert_contains "$out" "$expected" "$name refusal did not explain the marker problem"
  after=$(digest "$pending")
  [ "$before" = "$after" ] || fail "$name marker refusal changed the target"
}

test_marker_failures_leave_target_untouched() {
  assert_refusal missing 'missing marker' \
    $'# Queue\n<!-- BEGIN GENERATED: captain-queue -->\nold\n<!-- BEGIN APPEND-ONLY: captain-replies -->\n<!-- END APPEND-ONLY: captain-replies -->\n'
  assert_refusal malformed 'malformed marker' \
    $'# Queue\n<!-- BEGIN GENERATED: captain-queue --> extra\nold\n<!-- END GENERATED: captain-queue -->\n<!-- BEGIN APPEND-ONLY: captain-replies -->\n<!-- END APPEND-ONLY: captain-replies -->\n'
  assert_refusal nested 'nested markers' \
    $'# Queue\n<!-- BEGIN GENERATED: captain-queue -->\n<!-- BEGIN APPEND-ONLY: captain-replies -->\n<!-- END APPEND-ONLY: captain-replies -->\n<!-- END GENERATED: captain-queue -->\n'
  pass "missing, malformed, and nested markers refuse without changing the target"
}

run_case() { # <case-name> <function>
  case "${FM_PENDING_DECISIONS_TEST_ONLY:-all}" in
    all|"$1") "$2" ;;
  esac
}

run_case projection test_projection_preserves_manual_bytes_and_backlog
run_case detector test_reply_prefixes_wake_the_real_detector
run_case stable test_regeneration_is_stable_and_reply_append_only
run_case blocked-ordinary test_blocked_ordinary_hold_is_generated_once
run_case orphan test_unanswerable_orphan_is_visible_without_a_swallowed_prefix
run_case markers test_marker_failures_leave_target_untouched
